### ISSUE TITLE
Lower Performance on Wayland

### ISSUE THREAD

**Issue by JoeyDayy** [nmlynch94/com.jagexlauncher.JagexLauncher#33] opened 2024-05-25 16:28 UTC
Recently updated the Nvidia 555 driver and back ported explicit sync update for KDE but I'm noticing my fps is about half of what it was on X11. 

On X11 I had my fps capped at 100 and was pretty much locked using 117. But now on wayland I'm getting between 40-70 fps and is a lot less stable. 

I know there are patches for minecraft when faced with similar issues. Could similar patches or project Wakefield be used for osrs?

**Comment by nmlynch94** [comment] 2024-05-25 17:13
Thanks for the report. To clarify, did you also update to xwayland 24.1? Also do you still get the higher performance on x11 even after the driver upgrade?

I’ve had nothing but instability when it comes to wine + Wayland + Nvidia. I’ll have to look at this more closely since a lot of Nvidia users will be switching to Wayland soon.

**Comment by JoeyDayy** [comment] 2024-05-25 17:24
Yeah I updated xwayland to 24.1. 

I haven't tried loading x11 after upgrading my driver but I'll give it a try soon and let you know. 

Other apps I have running on wine such as steam games/lutris games are working and performing as expected.

**Comment by nmlynch94** [comment] 2024-05-25 17:29
Thank you! Yes proton seems to have solved a lot of those issues. Maybe I’ll test converting my flatpak to GEs new umu-launcher project and see if that helps. I’ve been planning to do that anyways. I wont be around until Sunday, but might be able to get a test build out for you to test if you’re willing.

I had never heard of project Wakefield but will take a look.

**Comment by JoeyDayy** [comment] 2024-05-25 18:02
I just logged into x11 and the performance was performing as well as it use to before updating my drivers so it is most likely a Wayland related issue.

I am more than happy to help out with testing and report back anything I observe and anything you would want me to look out for.

I didn't mention it earlier but thank you for maintaining this project

**Comment by nmlynch94** [comment] 2024-05-25 20:57
Ok thank you for checking that. Just wanted to confirm it was not the driver. 

No problem! I’m glad you find it useful. I’ll let you know when I have a working build.

**Comment by nmlynch94** [comment] 2024-05-27 07:57
@JoeyDayy So I'm seeing the same issue if I swap between x11 and wayland, at least the lower FPS part. I did not notice any other stability issues. I tested on both bolt launcher and the jagex launcher flatpak to make sure wine wasn't part of the issue. https://www.phoronix.com/review/wayland-nv-amd-2023/5. 

 I tried to build project wakefield, but did not finish. Will take a look at that option more. 

 Could you clarify what you mean by less stable? Are you getting crashes/other perf issues or do you mostly mean the FPS?

**Comment by JoeyDayy** [comment] 2024-05-27 10:28
I meant mostly fps stability where it fluctuates a lot. In terms of crashes or glitches I have not experienced any. 

I tested bolt launcher aswell and that sat at 98-100 the whole time regardless of what's on my screen. I do get no audio however hence why I use this project.

**Comment by nmlynch94** [comment] 2024-05-27 14:48
Ok then maybe the cause is jdk 11 vs 17. HDOS has a bug that stops the client from being able to launch due to a mis-quoted command line argument so we had to stay on 11 to support it. Adam chose to not support HDOS until they fixed it. I figured out a hack to get it working a few months back but never implemented it. I did now so latest version should have jdk17 so maybe that will help. Please let me know how it works after updating. If not, I have an umu-launcher version I can release next.

**Comment by JoeyDayy** [comment] 2024-05-27 16:10
Just gave it a try and it seemed to not make a difference

**Comment by nmlynch94** [comment] 2024-05-28 03:48
@JoeyDayy Thanks for testing. I've also put up an umu build in case that helps https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/releases/tag/umu-launch. You can just download that bundle and run `flatpak install --user <bundle-file>` I'm very confused as to how bolt would have better FPS. Theoretically, both applications are just launching using the same java flatpak extension natively on the OS.

**Comment by JoeyDayy** [comment] 2024-05-28 04:28
So i installed it and again performance wasn't improved however it broke my sound.
I had a similar issue with bolt launcher where they suggested to use pipewire instead of pulseaudio as a work around but I didn't want to do that. So I started to use this project instead.

It is something they're working on here: 
https://github.com/Adamcake/Bolt/issues/19

I was looking over at minecraft side and seeing what they did to fix java minecraft and saw something. Idk if it is something you can use but this post.
https://www.reddit.com/r/linux_gaming/comments/18r8x22/minecraft_running_purely_on_wayland_without/
Which in the comments reference this project to get libraries working properly.
https://github.com/BoyOrigin/glfw-wayland

**Comment by JoeyDayy** [comment] 2024-05-28 05:10
I just retested your updated version with bolts flatpak and it actually performs the same. (I fixed the sound issue) 
The bolt aur performs by far the best with about 30+ additional fps at the GE and 100 everywhere else but has no sound.

**Comment by nmlynch94** [comment] 2024-05-28 06:32
Ok that's really interesting. The main difference there would just be that the aur package uses your system libraries as opposed to the ones bundled in flatpak. What is the system java version you have installed?

As for that minecraft patch, I tried adding in the glfw-wayland patches to my flatpak locally. I had to pull out a patch set from PolyMC since it needed further modifications to work inside a flatpak container. It still ran via xwayland. Troubleshooting it outside of that is unfortunately outside of my technical capabilities, and I'm unclear if RuneScape even uses the glfw library that was being patched to facilitate running on wayland. 

One other thing to check - do you have the flatpak nvidia 555 driver? My understanding is that it's theoretically possible an older version could still work even if it doesn't match the host, but could cause degraded performance.

**Comment by JoeyDayy** [comment] 2024-05-28 06:37
I already tested java versions for the aur bolt by uninstalling all jre/jdk packages and one by one testing java 11, 17 and 22. All performed about the same. I have the 555 driver installed for flatpak since gpu/117 wouldn't enable without it. But I can try and remove any previous drivers

**Comment by JoeyDayy** [comment] 2024-05-28 06:45
Just uninstalled all drivers unrelated to 555

> $ flatpak list | grep -i nvidia
> nvidia-555-42-02        org.freedesktop.Platform.GL.nvidia-555-42-02            1.4     nvidia-555-42-021-origin        system
> nvidia-555-42-02        org.freedesktop.Platform.GL.nvidia-555-42-02            1.4     nvidia-555-42-021-origin        user
> nvidia-555-42-02        org.freedesktop.Platform.GL32.nvidia-555-42-02          1.4     nvidia-555-42-02-origin system
> nvidia-555-42-02        org.freedesktop.Platform.GL32.nvidia-555-42-02          1.4     nvidia-555-42-02-origin user

Same performance again

**Comment by nmlynch94** [comment] 2024-05-28 21:14
Unfortunately, it seems like Wayland + Nvidia + flatpak somehow just has worse performance.  We tried using the same openjdk as your system and it didn’t make a deifference so I’m not sure what else I’d be able to check.

**Comment by nmlynch94** [comment] 2024-05-29 00:59
Closing this since it seems not related to my specific implementation, and seems more like a general flatpak + wayland issue. Can reopen if you find anymore info.

**Closed as completed by nmlynch94** 2024-05-29 00:59 UTC
